services:
  auth-server:
    image: quay.io/keycloak/keycloak:26.2.0
    container_name: auth-server
    command:
      - start-dev
      - --import-realm
      - --health-enabled=true
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/:/opt/keycloak/data/import/
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8080
      KC_HOSTNAME_URL: http://localhost:8080
      KC_HOSTNAME_ADMIN_URL: http://localhost:8080
      KC_PROXY: edge
      KC_HOSTNAME_STRICT_BACKCHANNEL: true
      KC_HTTP_RELATIVE_PATH: /
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
    healthcheck:
      test: ['CMD-SHELL', '[ -f /tmp/HealthCheck.java ] || echo "public class HealthCheck { public static void main(String[] args) throws java.lang.Throwable { System.exit(java.net.HttpURLConnection.HTTP_OK == ((java.net.HttpURLConnection)new java.net.URL(args[0]).openConnection()).getResponseCode() ? 0 : 1); } }" > /tmp/HealthCheck.java && java /tmp/HealthCheck.java http://localhost:8080/auth/health/live']
      interval: 10s # Check every 10 seconds
      timeout: 5s   # Wait 5 seconds for response
      retries: 10   # Try 10 times before failing
      start_period: 30s # Allow 30 seconds initial startup time before first check

  demo-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: springboot-demo-image
    container_name: demo-app
    ports:
      - "8081:8081"
    depends_on:
      auth-server:
        condition: service_healthy